# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AKExtensionExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'AKSwifty/Extension'
  # Pods for AKExtensionExample

  target 'AKExtensionExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AKExtensionExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
