# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DashboardViewExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'AKSwifty/UIKit-DashboardView', '~>0.1.2'
  # Pods for DashboardViewExample

  target 'DashboardViewExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DashboardViewExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
